# Generated by Django 3.1.14 on 2023-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagePath',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
