# Generated by Django 3.1.14 on 2023-02-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20230222_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
