# Generated by Django 3.1.14 on 2023-02-25 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20230223_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skill_tableau',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 0, 15, 38, 234816, tzinfo=utc)),
        ),
    ]
